apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vch-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: vch-server
        image: begizi/vch-server:1.0.0
        env:
        - name: REDIS_URL
          value: redis
        ports:
        - containerPort: 8080
        - containerPort: 9001
